import base64
import os
from datetime import datetime
from typing import Dict, Any, Tuple


def _encode_image_to_base64(path: str) -> str:
    with open(path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode()


def generate_report(
    patient_info: Tuple[Any, ...],
    scan_info: Dict[str, Any],
    image_path: str,
    overlay_path: str | None,
) -> str:
    img_base64 = _encode_image_to_base64(image_path)

    overlay_base64 = ""
    if overlay_path and os.path.exists(overlay_path):
        overlay_base64 = _encode_image_to_base64(overlay_path)

    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>CURASCAN Diagnostic Report</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            .header {{ text-align: center; color: #2E86AB; }}
            .patient-info {{ background: #f0f2f6; padding: 20px; border-radius: 8px; margin: 20px 0; }}
            .scan-info {{ background: #e8f4f8; padding: 20px; border-radius: 8px; margin: 20px 0; }}
            .images {{ display: flex; justify-content: space-around; margin: 20px 0; }}
            .image-container {{ text-align: center; }}
            img {{ max-width: 400px; border: 2px solid #ddd; border-radius: 8px; }}
        </style>
    </head>
    <body>
        <div class="header">
            <h1>🏥 CURASCAN</h1>
            <h2>Medical Imaging Diagnostic Report</h2>
            <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>

        <div class="patient-info">
            <h3>Patient Information</h3>
            <p><strong>Patient ID:</strong> {patient_info[1]}</p>
            <p><strong>Name:</strong> {patient_info[2]}</p>
            <p><strong>DOB:</strong> {patient_info[3]}</p>
            <p><strong>Gender:</strong> {patient_info[4]}</p>
            <p><strong>Clinical Notes:</strong> {patient_info[5]}</p>
        </div>

        <div class="scan-info">
            <h3>Scan Analysis</h3>
            <p><strong>Scan Type:</strong> {scan_info['type']}</p>
            <p><strong>AI Result:</strong> {scan_info['result']}</p>
            <p><strong>Confidence:</strong> {scan_info['confidence']:.2%}</p>
            <p><strong>Upload Date:</strong> {scan_info['date']}</p>
        </div>

        <div class="images">
            <div class="image-container">
                <h4>Original Scan</h4>
                <img src="data:image/png;base64,{img_base64}" />
            </div>
            {f'<div class="image-container"><h4>AI Analysis Overlay</h4><img src="data:image/png;base64,{overlay_base64}" /></div>' if overlay_base64 else ''}
        </div>

        <div style="margin-top: 40px; padding: 20px; border-top: 2px solid #ddd;">
            <p><em>This report is generated by CURASCAN AI diagnostic system.</em></p>
        </div>
    </body>
    </html>
    """
    return html_content

